### ISSUE TITLE
Finicky parser

### ISSUE THREAD

**Issue by kokarn** [benji7425/discord-bot-rss-feed#1]
Hey!

Have a guy trying to integrate an RSS feed I publish for the ARK Dev tracker but the bot refuses.
It seems to be that the parser you use is super-outdated and a bit finicky with special stuff in the feeds.

Here's the feed: https://arkdevtracker.com/rss
It's valid but does contain some non-standard features.

Would it be too much to ask that you switch parser?
I've used [feedme](https://www.npmjs.com/package/feedme) before which is still in active development and works great.

**Comment by benji7425** [comment]
Definitely willing to take a look into this, I don't know much about RSS myself to be honest so not too surprised to hear that the parser I used mightn't have been the best one. Will try it out in the new year.

**Comment by kokarn** [comment]
Cool! Yeah, it's a bit tricky because so much is allowed but non-standard. Shouldn't be too much work either and if you need any help just let me know.

**Comment by benji7425** [comment]
I've updated the bot to use [rss-parser](https://www.npmjs.com/package/rss-parser) instead of the old [feed-read](https://www.npmjs.com/package/feed-read) module. I used this one over the one you suggested due to syntactic similarities with feed-read meaning fewer code changes on my part, so less chance to introduce more errors :p

Tested with the RSS feed demoed, and it's working fine! Will push a new release with this update shortly

**Comment by kokarn** [comment]
Yeah, I'm fine with whatever actually. It was just a suggestion of one I know that works ^^

Glad to see the progress!
